services:
  postgres:
    image: postgres:latest
    container_name: lyo-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - lyo-network

  redis:
    image: redis/redis-stack:latest
    container_name: lyo-redis
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    networks:
      - lyo-network

  localstack:
    image: localstack/localstack:latest
    container_name: lyo-localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init-s3.sh
    networks:
      - lyo-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
  localstack_data:
    driver: local

networks:
  lyo-network:
    driver: bridge
